namespace GolfLeague.Domain.Entities;

/// <summary>
/// A single round-robin match-play pairing between two players within a
/// flight, for one week's Round, in a match-play-format half. Generated by
/// GenerateMatchPlayScheduleCommand from the round-robin circle method.
/// Player2Id is null to represent a bye (odd player count) — Player1 plays
/// against the card that week.
/// </summary>
public class FlightMatch
{
    public int Id { get; set; }
    public int FlightId { get; set; }
    public int HalfId { get; set; }
    public int RoundId { get; set; }
    public int WeekNumber { get; set; }
    public int Player1Id { get; set; }
    public int? Player2Id { get; set; }

    /// <summary>
    /// True when the corresponding player skipped the week (RoundParticipant.SkippedWeek)
    /// and the match was scored against the card for the other side. Denormalized at
    /// scoring time for quick display; source of truth remains RoundParticipant.SkippedWeek.
    /// </summary>
    public bool Player1Absent { get; set; }
    public bool Player2Absent { get; set; }

    /// <summary>Total match points awarded to each player once scored. Null until computed.</summary>
    public int? Player1Points { get; set; }
    public int? Player2Points { get; set; }

    /// <summary>Holes won by each player (used for the 4-point overall bonus and display). Null until computed.</summary>
    public int? Player1HolesWon { get; set; }
    public int? Player2HolesWon { get; set; }

    public Flight Flight { get; set; } = null!;
    public SeasonHalf Half { get; set; } = null!;
    public Round Round { get; set; } = null!;
    public Player Player1 { get; set; } = null!;
    public Player? Player2 { get; set; }
    public ICollection<FlightMatchHoleResult> HoleResults { get; set; } = [];
}
